spring:
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${AWS_MYSQL_URL}
      username: root
      password: ${AWS_MYSQL_PASSWORD}

    secondary:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${AWS_POSTGRESQL_URL}
      username: postgres
      password: ${AWS_POSTGRESQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    generate-ddl: true
#    hibernate:
#      ddl-auto: create

  mail:
    host: smtp.gmail.com
    port: 587
    username: mjuappsw@gmail.com
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  cloud:
    aws:
      credentials:
        access-key: ${AWS_S3_ACCESS_KEY}
        secret-key: ${AWS_S3_SECRET_KEY}
      region:
        static: ap-northeast-2
        auto: false
      stack:
        auto: false
      s3:
        bucket: j-project-2023

#  sql:
#    init:
#      mode: always
