spring:
  profiles:
    active: prod

  datasource:
    primary:
      hibernate:
        hbm2ddl:
#          auto: create #개발 환경일 때
          auto: validate #운영 환경일 때
    secondary:
      hibernate:
        hbm2ddl:
#          auto: create #개발 환경일 때
          auto: validate #운영 환경일 때
